---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "frank-framework.fullname" . }}-env
  labels:
    {{- include "frank-framework.labels" . | nindent 4 }}
data:
  configurations.names: {{ .Values.frank.configurations.names | default "" }}
  {{- if .Values.frank.properties }}
  {{ .Values.frank.properties | toYaml | nindent 2 }}
  {{- end }}
