apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frank-framework.fullname" . }}
  labels:
    {{- include "frank-framework.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frank-framework.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "frank-framework.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "frank-framework.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "frank-framework.fullname" . }}-env
          volumeMounts:
            - name: {{ template "frank-framework.fullname" . }}-config
              mountPath: /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
              subPath: context.xml
              readOnly: true
            {{- if .Values.frank.credentials }}
            - name: {{ template "frank-framework.fullname" . }}-credentials
              mountPath: /opt/frank/secrets/
              readOnly: true
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /iaf/
              port: http
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ template "frank-framework.fullname" . }}-config
          configMap:
            name: {{ template "frank-framework.fullname" . }}-config
        {{- if .Values.frank.credentials }}
        - name: {{ template "frank-framework.fullname" . }}-credentials
          secret: 
            secretName: {{ .Values.frank.credentials.secret }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
