apiVersion: v2
appVersion: "7.8"
description: A Helm chart for running the Frank!Framework on Kubernetes
name: frank-framework
icon: https://raw.githubusercontent.com/frankframework/charts/master/charts/frank-framework/icon.svg
type: application
version: 0.2.9
deprecated: true

dependencies:
  - name: ff-common
    version: ~0.1.17
    repository: file://../ff-common
