{{- template "ff-common.deployment" (list . "ff-test.deployment") -}}
{{- define "ff-test.deployment" -}}
spec:
  template:
    metadata:
      annotations:
        checksum/configmap.context: {{ include (print $.Template.BasePath "/configmap.context.yaml") . | sha256sum }}
        checksum/configmap.env: {{ include (print $.Template.BasePath "/configmap.env.yaml") . | sha256sum }}
    spec:
      containers:
        -
          {{ include "ff-common.container" (list . "ff-test.deployment.container") | nindent 10}}
{{- end -}}
{{- define "ff-test.deployment.container" -}}
volumeMounts:
  {{- if .Values.securityContext.readOnlyRootFilesystem }}
  - mountPath: /usr/local/tomcat/logs
    name: tmpfs
  - mountPath: /usr/local/tomcat/conf/Catalina
    name: tmpfs
  - mountPath: /usr/local/tomcat/work/Catalina/localhost
    name: tmpfs
  - mountPath: /usr/local/tomcat/temp
    name: tmpfs
  {{- end }}
  {{- if .Values.frank.security.http.localUsers }}
  - name: {{ template "ff-common.fullname" . }}-tomcat-users
    mountPath: /usr/local/tomcat/conf/tomcat-users.xml
    subPath: tomcat-users.xml
    readOnly: true
  {{- end }}
  {{- if .Values.frank.security.http.activeDirectory.enabled }}
  - name: {{ template "ff-common.fullname" . }}-ldap-role-mapping
    mountPath: /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/ldap-role-mapping.properties
    subPath: ldap-role-mapping.properties
    readOnly: true
  {{- end }}
  {{- if .Values.frank.credentials.secret }}
  - name: {{ template "ff-common.fullname" . }}-credentials
    mountPath: /opt/frank/secrets/
    readOnly: true
  {{- end }}
  {{- if .Values.connections.create }}
  - name: {{ template "ff-common.fullname" . }}-context
    mountPath: /usr/local/tomcat/conf/Catalina/localhost/iaf-test.xml
    subPath: context.xml
    readOnly: true
  {{- end }}
livenessProbe:
  httpGet:
    path: /iaf-test/iaf/gui
    port: 8080
{{- end -}}