apiVersion: v2
name: ff-test
description: A Helm chart for testing the Frank!Framework on Kubernetes
version: 0.2.30
appVersion: "latest-tomcat"
type: application
home: https://frankframework.org
icon: https://raw.githubusercontent.com/frankframework/charts/master/charts/ff-test/icon.svg

keywords:
  - e2e

dependencies:
  - name: ff-common
    version: ~0.1.18
    repository: file://../ff-common
